# Acid 0.1.0 — Lactic, for fish
#
# Generated by acid from ports/fish/theme.tera. Do not edit; edit the
# template, or the palette in crates/acid-palette/src/lib.rs, and re-run
# `make`.
#
# These are global rather than universal variables, so the theme lives in
# tracked config and survives on any machine. Drop this in ~/.config/fish/conf.d
# and it applies on the next shell.

# Syntax highlighting
set -g fish_color_normal 3a3117
set -g fish_color_command 4a8143
set -g fish_color_keyword bc4d77
set -g fish_color_quote 737914
set -g fish_color_redirection bc4d77
set -g fish_color_end bc4d77
set -g fish_color_error df2910
set -g fish_color_param 3a3117
set -g fish_color_option 4978a4
set -g fish_color_comment 877e71 --italics
set -g fish_color_operator bc4d77
set -g fish_color_escape bd560b
set -g fish_color_autosuggestion 9a958a
set -g fish_color_cancel df2910
set -g fish_color_gray 877e71
set -g fish_color_selection 3a3117 --background=b4ada2
set -g fish_color_search_match --background=b4ada2
set -g fish_color_match 9c6a0e
set -g fish_color_valid_path --underline
set -g fish_color_history_current --bold

# Prompt
set -g fish_color_cwd 4978a4
set -g fish_color_cwd_root df2910
set -g fish_color_user 4a8143
set -g fish_color_host 4978a4
set -g fish_color_host_remote 9c6a0e
set -g fish_color_status df2910

# Completion pager. The pager background is left unset so it inherits the
# terminal's own, which keeps a transparent terminal transparent.
set -g fish_pager_color_prefix 4a8143 --bold
set -g fish_pager_color_completion 4f4430
set -g fish_pager_color_description 877e71
set -g fish_pager_color_progress 5f5647 --background=e3e1dd
set -g fish_pager_color_search_match --background=b4ada2
set -g fish_pager_color_selected_background --background=b4ada2
set -g fish_pager_color_selected_prefix 4a8143 --bold
set -g fish_pager_color_selected_completion 3a3117
set -g fish_pager_color_selected_description 5f5647
set -g fish_pager_color_secondary_background --background=e3e1dd
set -g fish_pager_color_secondary_prefix 4a8143
set -g fish_pager_color_secondary_completion 4f4430
set -g fish_pager_color_secondary_description 877e71
